version: "3.9"
services:
  database:
    container_name: friendsmgmt-pg
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    container_name: friendsmgmt-api
    ports:
      - "3003:3003"
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  data:
